connector_type: kafka
bootstrap_server: "{{ env_var('KAFKA_BOOTSTRAP_SERVERS') }}"
topic: "{{ env_var('KAFKA_EVENTS_TOPIC', 'clickstream-events') }}"
consumer_group: "{{ env_var('POSTGRESQL_CONSUMER_GROUP_ID', 'clickstream-postgresql') }}"
batch_size: 1000
timeout_ms: 250
